package br.com.shiroshima.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("User Entity Tests")
class UserTest {

    private User user;

    @Test
    @DisplayName("Should create User with default constructor")
    void shouldCreateUserWithDefaultConstructor() {
        User user = new User();

        assertNotNull(user);
        assertNull(user.getId());
        assertNull(user.getUsername());
        assertNull(user.getPassword());
        assertNull(user.getBio());
    }

    @Test
    @DisplayName("Should create User with parameterized constructor")
    void shouldCreateUserWithParameterizedConstructor() {
        String username = "testuser";
        String password = "hashedPassword123";
        String bio = "Test bio";

        User user = new User(username, password, bio);

        assertNotNull(user);
        assertNull(user.getId()); // ID is generated by database
        assertEquals(username, user.getUsername());
        assertEquals(password, user.getPassword());
        assertEquals(bio, user.getBio());
    }

    @Test
    @DisplayName("Should create User with null bio")
    void shouldCreateUserWithNullBio() {
        User user = new User("testuser", "password", null);

        assertNotNull(user);
        assertEquals("testuser", user.getUsername());
        assertEquals("password", user.getPassword());
        assertNull(user.getBio());
    }

    @Test
    @DisplayName("Should create User with null values")
    void shouldCreateUserWithNullValues() {
        User user = new User(null, null, null);

        assertNotNull(user);
        assertNull(user.getUsername());
        assertNull(user.getPassword());
        assertNull(user.getBio());
    }

    @BeforeEach
    void setUp() {
        user = new User();
    }

    @Test
    @DisplayName("Should set and get ID")
    void shouldSetAndGetId() {
        Long id = 1L;
        user.setId(id);

        assertEquals(id, user.getId());
    }

    @Test
    @DisplayName("Should set and get username")
    void shouldSetAndGetUsername() {
        String username = "johndoe";
        user.setUsername(username);

        assertEquals(username, user.getUsername());
    }

    @Test
    @DisplayName("Should set and get password")
    void shouldSetAndGetPassword() {
        String password = "hashedPassword";
        user.setPassword(password);

        assertEquals(password, user.getPassword());
    }

    @Test
    @DisplayName("Should set and get bio")
    void shouldSetAndGetBio() {
        String bio = "Music enthusiast";
        user.setBio(bio);

        assertEquals(bio, user.getBio());
    }


    @Test
    @DisplayName("Should allow null bio")
    void shouldAllowNullBio() {
        user.setBio(null);
        assertNull(user.getBio());
    }

    @Test
    @DisplayName("Should update existing values")
    void shouldUpdateExistingValues() {
        user.setUsername("oldname");
        user.setUsername("newname");

        assertEquals("newname", user.getUsername());
    }


    @Test
    @DisplayName("Should return true when comparing same object")
    void shouldReturnTrueForSameObject() {
        User user = new User("testuser", "password", "bio");
        user.setId(1L);

        assertEquals(user, user);
    }

    @Test
    @DisplayName("Should return true when IDs are equal")
    void shouldReturnTrueForEqualIds() {
        User user1 = new User("user1", "password1", "bio1");
        user1.setId(1L);

        User user2 = new User("user2", "password2", "bio2");
        user2.setId(1L);

        assertEquals(user1, user2);
        assertEquals(user2, user1);
    }

    @Test
    @DisplayName("Should return false when IDs are different")
    void shouldReturnFalseForDifferentIds() {
        User user1 = new User("user1", "password1", "bio1");
        user1.setId(1L);

        User user2 = new User("user1", "password1", "bio1");
        user2.setId(2L);

        assertNotEquals(user1, user2);
        assertNotEquals(user2, user1);
    }

    @Test
    @DisplayName("Should return false when comparing with null")
    void shouldReturnFalseForNull() {
        User user = new User("testuser", "password", "bio");
        user.setId(1L);

        assertNotEquals(null, user);
    }

    @Test
    @DisplayName("Should return false when comparing with different class")
    void shouldReturnFalseForDifferentClass() {
        User user = new User("testuser", "password", "bio");
        user.setId(1L);

        String notAUser = "Not a User";

        assertNotEquals(user, notAUser);
    }

    @Test
    @DisplayName("Should return false when one ID is null")
    void shouldReturnFalseWhenOneIdIsNull() {
        User user1 = new User("user1", "password1", "bio1");
        user1.setId(1L);

        User user2 = new User("user2", "password2", "bio2");
        user2.setId(null);

        assertNotEquals(user1, user2);
        assertNotEquals(user2, user1);
    }

    @Test
    @DisplayName("Should return true when both IDs are null")
    void shouldReturnTrueWhenBothIdsAreNull() {
        User user1 = new User("user1", "password1", "bio1");
        User user2 = new User("user2", "password2", "bio2");

        assertEquals(user1, user2);
    }


    @Test
    @DisplayName("Should return same hashCode for same ID")
    void shouldReturnSameHashCodeForSameId() {
        User user1 = new User("user1", "password1", "bio1");
        user1.setId(1L);

        User user2 = new User("user2", "password2", "bio2");
        user2.setId(1L);

        assertEquals(user1.hashCode(), user2.hashCode());
    }

    @Test
    @DisplayName("Should return consistent hashCode")
    void shouldReturnConsistentHashCode() {
        User user = new User("testuser", "password", "bio");
        user.setId(1L);

        int firstHashCode = user.hashCode();
        int secondHashCode = user.hashCode();

        assertEquals(firstHashCode, secondHashCode);
    }

    @Test
    @DisplayName("Should return different hashCode for different IDs")
    void shouldReturnDifferentHashCodeForDifferentIds() {
        User user1 = new User("user1", "password1", "bio1");
        user1.setId(1L);

        User user2 = new User("user2", "password2", "bio2");
        user2.setId(2L);

        assertNotEquals(user1.hashCode(), user2.hashCode());
    }

    @Test
    @DisplayName("Should handle null ID in hashCode")
    void shouldHandleNullIdInHashCode() {
        User user = new User("testuser", "password", "bio");

        assertDoesNotThrow(user::hashCode);
    }

    @Test
    @DisplayName("Should satisfy equals-hashCode contract")
    void shouldSatisfyEqualsHashCodeContract() {
        User user1 = new User("user1", "password1", "bio1");
        user1.setId(1L);

        User user2 = new User("user2", "password2", "bio2");
        user2.setId(1L);

        // If two objects are equal, they must have the same hashCode
        if (user1.equals(user2)) {
            assertEquals(user1.hashCode(), user2.hashCode());
        }
    }


    @Test
    @DisplayName("Should contain username in toString")
    void shouldContainUsernameInToString() {
        User user = new User("johndoe", "password", "Music lover");
        user.setId(1L);

        String result = user.toString();

        assertTrue(result.contains("johndoe"));
    }

    @Test
    @DisplayName("Should contain ID in toString")
    void shouldContainIdInToString() {
        User user = new User("johndoe", "password", "Music lover");
        user.setId(42L);

        String result = user.toString();

        assertTrue(result.contains("42"));
    }

    @Test
    @DisplayName("Should contain bio in toString")
    void shouldContainBioInToString() {
        User user = new User("johndoe", "password", "Music lover");
        user.setId(1L);

        String result = user.toString();

        assertTrue(result.contains("Music lover"));
    }

    @Test
    @DisplayName("Should not contain password in toString - security check")
    void shouldNotContainPasswordInToString() {
        User user = new User("johndoe", "secretPassword123", "Music lover");
        user.setId(1L);

        String result = user.toString();

        assertFalse(result.contains("secretPassword123"));
        assertFalse(result.contains("password="));
    }

    @Test
    @DisplayName("Should handle null values in toString")
    void shouldHandleNullValuesInToString() {
        User user = new User(null, null, null);

        assertDoesNotThrow(user::toString);
    }

    @Test
    @DisplayName("Should return non-null string")
    void shouldReturnNonNullString() {
        User user = new User("testuser", "password", "bio");

        String result = user.toString();

        assertNotNull(result);
    }


    @Test
    @DisplayName("Should accept username with maximum length of 20 characters")
    void shouldAcceptUsernameWithMaxLength() {
        String username = "12345678901234567890"; // 20 chars
        User user = new User(username, "password", "bio");

        assertEquals(20, user.getUsername().length());
        assertEquals(username, user.getUsername());
    }

    @Test
    @DisplayName("Should accept username with less than 20 characters")
    void shouldAcceptUsernameWithLessThanMaxLength() {
        String username = "shortname";
        User user = new User(username, "password", "bio");

        assertTrue(user.getUsername().length() < 20);
        assertEquals(username, user.getUsername());
    }

    @Test
    @DisplayName("Should accept empty bio")
    void shouldAcceptEmptyBio() {
        User user = new User("testuser", "password", "");

        assertEquals("", user.getBio());
    }

    @Test
    @DisplayName("Should accept long bio")
    void shouldAcceptLongBio() {
        String longBio = "This is a very long bio that contains lots of information about the user's musical preferences and background.";
        User user = new User("testuser", "password", longBio);

        assertEquals(longBio, user.getBio());
    }

    @Test
    @DisplayName("Should maintain immutability of User object through setters")
    void shouldMaintainUserObjectThroughSetters() {
        User user = new User("original", "password", "bio");
        user.setId(1L);

        Long originalId = user.getId();
        user.setUsername("modified");
        user.setPassword("newPassword");
        user.setBio("new bio");

        assertEquals(originalId, user.getId());

        assertEquals("modified", user.getUsername());
        assertEquals("newPassword", user.getPassword());
        assertEquals("new bio", user.getBio());
    }

    @Test
    @DisplayName("Should create independent User objects")
    void shouldCreateIndependentUserObjects() {
        User user1 = new User("user1", "password1", "bio1");
        User user2 = new User("user2", "password2", "bio2");

        user1.setUsername("modified");

        assertEquals("modified", user1.getUsername());
        assertEquals("user2", user2.getUsername());
    }

}

